//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchiSteamFarm.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArchiSteamFarm.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accepting trade: {0}.
        /// </summary>
        public static string AcceptingTrade {
            get {
                return ResourceManager.GetString("AcceptingTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Matching Steam items, round #{0}....
        /// </summary>
        public static string ActivelyMatchingItems {
            get {
                return ResourceManager.GetString("ActivelyMatchingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Matched a total of {0} sets this round..
        /// </summary>
        public static string ActivelyMatchingItemsRound {
            get {
                return ResourceManager.GetString("ActivelyMatchingItemsRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} config file will be migrated to the latest syntax....
        /// </summary>
        public static string AutomaticFileMigration {
            get {
                return ResourceManager.GetString("AutomaticFileMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ASF will automatically check for new versions every {0}..
        /// </summary>
        public static string AutoUpdateCheckInfo {
            get {
                return ResourceManager.GetString("AutoUpdateCheckInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accepted donation trade: {0}.
        /// </summary>
        public static string BotAcceptedDonationTrade {
            get {
                return ResourceManager.GetString("BotAcceptedDonationTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accepting gift: {0}....
        /// </summary>
        public static string BotAcceptingGift {
            get {
                return ResourceManager.GetString("BotAcceptingGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account is no longer occupied: farming process resumed!.
        /// </summary>
        public static string BotAccountFree {
            get {
                return ResourceManager.GetString("BotAccountFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This account is limited, farming process is unavailable until the restriction is removed!.
        /// </summary>
        public static string BotAccountLimited {
            get {
                return ResourceManager.GetString("BotAccountLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This account is locked, farming process is permanently unavailable!.
        /// </summary>
        public static string BotAccountLocked {
            get {
                return ResourceManager.GetString("BotAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account is currently being used: ASF will resume farming when it&apos;s free....
        /// </summary>
        public static string BotAccountOccupied {
            get {
                return ResourceManager.GetString("BotAccountOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID: {0} | Status: {1}.
        /// </summary>
        public static string BotAddLicense {
            get {
                return ResourceManager.GetString("BotAddLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID: {0} | Status: {1} | Items: {2}.
        /// </summary>
        public static string BotAddLicenseWithItems {
            get {
                return ResourceManager.GetString("BotAddLicenseWithItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This bot is already running!.
        /// </summary>
        public static string BotAlreadyRunning {
            get {
                return ResourceManager.GetString("BotAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This bot has already stopped!.
        /// </summary>
        public static string BotAlreadyStopped {
            get {
                return ResourceManager.GetString("BotAlreadyStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Converting .maFile into ASF format....
        /// </summary>
        public static string BotAuthenticatorConverting {
            get {
                return ResourceManager.GetString("BotAuthenticatorConverting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Successfully finished importing mobile authenticator!.
        /// </summary>
        public static string BotAuthenticatorImportFinished {
            get {
                return ResourceManager.GetString("BotAuthenticatorImportFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2FA Token: {0}.
        /// </summary>
        public static string BotAuthenticatorToken {
            get {
                return ResourceManager.GetString("BotAuthenticatorToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Automatic farming has paused!.
        /// </summary>
        public static string BotAutomaticIdlingNowPaused {
            get {
                return ResourceManager.GetString("BotAutomaticIdlingNowPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Automatic farming has resumed!.
        /// </summary>
        public static string BotAutomaticIdlingNowResumed {
            get {
                return ResourceManager.GetString("BotAutomaticIdlingNowResumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Automatic farming is paused already!.
        /// </summary>
        public static string BotAutomaticIdlingPausedAlready {
            get {
                return ResourceManager.GetString("BotAutomaticIdlingPausedAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Automatic farming is resumed already!.
        /// </summary>
        public static string BotAutomaticIdlingResumedAlready {
            get {
                return ResourceManager.GetString("BotAutomaticIdlingResumedAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connected to Steam!.
        /// </summary>
        public static string BotConnected {
            get {
                return ResourceManager.GetString("BotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connecting....
        /// </summary>
        public static string BotConnecting {
            get {
                return ResourceManager.GetString("BotConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection to Steam Network lost. Reconnecting....
        /// </summary>
        public static string BotConnectionLost {
            get {
                return ResourceManager.GetString("BotConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disconnected from Steam!.
        /// </summary>
        public static string BotDisconnected {
            get {
                return ResourceManager.GetString("BotDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disconnecting....
        /// </summary>
        public static string BotDisconnecting {
            get {
                return ResourceManager.GetString("BotDisconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [{0}] password: {1}.
        /// </summary>
        public static string BotEncryptedPassword {
            get {
                return ResourceManager.GetString("BotEncryptedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Waiting up to {0} to ensure that we&apos;re free to start farming....
        /// </summary>
        public static string BotExtraIdlingCooldown {
            get {
                return ResourceManager.GetString("BotExtraIdlingCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bot has {0} games remaining in its background queue..
        /// </summary>
        public static string BotGamesToRedeemInBackgroundCount {
            get {
                return ResourceManager.GetString("BotGamesToRedeemInBackgroundCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generating Steam parental code, this can take a while, consider putting it in the config instead....
        /// </summary>
        public static string BotGeneratingSteamParentalCode {
            get {
                return ResourceManager.GetString("BotGeneratingSteamParentalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Successfully handled {0} confirmations!.
        /// </summary>
        public static string BotHandledConfirmations {
            get {
                return ResourceManager.GetString("BotHandledConfirmations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bot has no wallet..
        /// </summary>
        public static string BotHasNoWallet {
            get {
                return ResourceManager.GetString("BotHasNoWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to disconnect the client. Abandoning this bot instance!.
        /// </summary>
        public static string BotHeartBeatFailed {
            get {
                return ResourceManager.GetString("BotHeartBeatFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Playing selected {0}: {1}.
        /// </summary>
        public static string BotIdlingSelectedGames {
            get {
                return ResourceManager.GetString("BotIdlingSelectedGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not starting this bot instance because it&apos;s disabled in config file!.
        /// </summary>
        public static string BotInstanceNotStartingBecauseDisabled {
            get {
                return ResourceManager.GetString("BotInstanceNotStartingBecauseDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Received TwoFactorCodeMismatch error code {0} times in a row. Either your 2FA credentials are no longer valid, or your clock is out of sync, aborting!.
        /// </summary>
        public static string BotInvalidAuthenticatorDuringLogin {
            get {
                return ResourceManager.GetString("BotInvalidAuthenticatorDuringLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Received InvalidPassword error code {0} times in a row. Your password for this account is most likely wrong, aborting!.
        /// </summary>
        public static string BotInvalidPasswordDuringLogin {
            get {
                return ResourceManager.GetString("BotInvalidPasswordDuringLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bot has level {0}..
        /// </summary>
        public static string BotLevel {
            get {
                return ResourceManager.GetString("BotLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logged off of Steam: {0}.
        /// </summary>
        public static string BotLoggedOff {
            get {
                return ResourceManager.GetString("BotLoggedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Successfully logged on as {0}..
        /// </summary>
        public static string BotLoggedOn {
            get {
                return ResourceManager.GetString("BotLoggedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logging in....
        /// </summary>
        public static string BotLoggingIn {
            get {
                return ResourceManager.GetString("BotLoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This account seems to be used in another ASF instance, which is undefined behaviour, refusing to keep it running!.
        /// </summary>
        public static string BotLogonSessionReplaced {
            get {
                return ResourceManager.GetString("BotLogonSessionReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trade offer failed!.
        /// </summary>
        public static string BotLootingFailed {
            get {
                return ResourceManager.GetString("BotLootingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trade couldn&apos;t be sent because there is no user with master permission defined!.
        /// </summary>
        public static string BotLootingMasterNotDefined {
            get {
                return ResourceManager.GetString("BotLootingMasterNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trade offer sent successfully!.
        /// </summary>
        public static string BotLootingSuccess {
            get {
                return ResourceManager.GetString("BotLootingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This bot doesn&apos;t have ASF 2FA enabled! Did you forget to import your authenticator as ASF 2FA?.
        /// </summary>
        public static string BotNoASFAuthenticator {
            get {
                return ResourceManager.GetString("BotNoASFAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This bot instance is not connected!.
        /// </summary>
        public static string BotNotConnected {
            get {
                return ResourceManager.GetString("BotNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Couldn&apos;t find any bot named {0}!.
        /// </summary>
        public static string BotNotFound {
            get {
                return ResourceManager.GetString("BotNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not owned yet: {0}.
        /// </summary>
        public static string BotNotOwnedYet {
            get {
                return ResourceManager.GetString("BotNotOwnedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Owned already: {0}.
        /// </summary>
        public static string BotOwnedAlready {
            get {
                return ResourceManager.GetString("BotOwnedAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Owned already: {0} | {1}.
        /// </summary>
        public static string BotOwnedAlreadyWithName {
            get {
                return ResourceManager.GetString("BotOwnedAlreadyWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}/{1} bots already own game {2}..
        /// </summary>
        public static string BotOwnsOverviewPerGame {
            get {
                return ResourceManager.GetString("BotOwnsOverviewPerGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Points balance: {0}.
        /// </summary>
        public static string BotPointsBalance {
            get {
                return ResourceManager.GetString("BotPointsBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rate limit exceeded, we will retry after {0} of cooldown....
        /// </summary>
        public static string BotRateLimitExceeded {
            get {
                return ResourceManager.GetString("BotRateLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reconnecting....
        /// </summary>
        public static string BotReconnecting {
            get {
                return ResourceManager.GetString("BotReconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key: {0} | Status: {1}.
        /// </summary>
        public static string BotRedeem {
            get {
                return ResourceManager.GetString("BotRedeem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key: {0} | Status: {1} | Items: {2}.
        /// </summary>
        public static string BotRedeemWithItems {
            get {
                return ResourceManager.GetString("BotRedeemWithItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refreshing packages data....
        /// </summary>
        public static string BotRefreshingPackagesData {
            get {
                return ResourceManager.GetString("BotRefreshingPackagesData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Removed expired login key!.
        /// </summary>
        public static string BotRemovedExpiredLoginKey {
            get {
                return ResourceManager.GetString("BotRemovedExpiredLoginKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can&apos;t send a trade to yourself!.
        /// </summary>
        public static string BotSendingTradeToYourself {
            get {
                return ResourceManager.GetString("BotSendingTradeToYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current memory usage: {0} MB.
        ///Process uptime: {1}.
        /// </summary>
        public static string BotStats {
            get {
                return ResourceManager.GetString("BotStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bot is connecting to Steam network..
        /// </summary>
        public static string BotStatusConnecting {
            get {
                return ResourceManager.GetString("BotStatusConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bot is farming game: {0} ({1}, {2} card drops remaining) from a total of {3} games ({4} cards) left to farm (~{5} remaining)..
        /// </summary>
        public static string BotStatusIdling {
            get {
                return ResourceManager.GetString("BotStatusIdling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bot is farming games: {0} from a total of {1} games ({2} cards) left to farm (~{3} remaining)..
        /// </summary>
        public static string BotStatusIdlingList {
            get {
                return ResourceManager.GetString("BotStatusIdlingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bot is limited and can&apos;t drop any cards through farming..
        /// </summary>
        public static string BotStatusLimited {
            get {
                return ResourceManager.GetString("BotStatusLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bot is locked and can&apos;t drop any cards through farming..
        /// </summary>
        public static string BotStatusLocked {
            get {
                return ResourceManager.GetString("BotStatusLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bot is not farming anything..
        /// </summary>
        public static string BotStatusNotIdling {
            get {
                return ResourceManager.GetString("BotStatusNotIdling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bot is not running..
        /// </summary>
        public static string BotStatusNotRunning {
            get {
                return ResourceManager.GetString("BotStatusNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are {0}/{1} bots running, with total of {2} games ({3} cards) left to farm..
        /// </summary>
        public static string BotStatusOverview {
            get {
                return ResourceManager.GetString("BotStatusOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bot is paused or running in manual mode..
        /// </summary>
        public static string BotStatusPaused {
            get {
                return ResourceManager.GetString("BotStatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bot is currently being used..
        /// </summary>
        public static string BotStatusPlayingNotAvailable {
            get {
                return ResourceManager.GetString("BotStatusPlayingNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not initialize SteamDirectory: connecting with Steam Network might take much longer than usual!.
        /// </summary>
        public static string BotSteamDirectoryInitializationFailed {
            get {
                return ResourceManager.GetString("BotSteamDirectoryInitializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stopping....
        /// </summary>
        public static string BotStopping {
            get {
                return ResourceManager.GetString("BotStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The trade offer {0} is determined to be {1} due to {2}..
        /// </summary>
        public static string BotTradeOfferResult {
            get {
                return ResourceManager.GetString("BotTradeOfferResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to login to Steam: {0}/{1}.
        /// </summary>
        public static string BotUnableToLogin {
            get {
                return ResourceManager.GetString("BotUnableToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} V{1}.
        /// </summary>
        public static string BotVersion {
            get {
                return ResourceManager.GetString("BotVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wallet balance: {0} {1}.
        /// </summary>
        public static string BotWalletBalance {
            get {
                return ResourceManager.GetString("BotWalletBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Checking first badge page....
        /// </summary>
        public static string CheckingFirstBadgePage {
            get {
                return ResourceManager.GetString("CheckingFirstBadgePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Checking other badge pages....
        /// </summary>
        public static string CheckingOtherBadgePages {
            get {
                return ResourceManager.GetString("CheckingOtherBadgePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chosen farming algorithm: {0}.
        /// </summary>
        public static string ChosenFarmingAlgorithm {
            get {
                return ResourceManager.GetString("ChosenFarmingAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clearing Steam discovery queue #{0}....
        /// </summary>
        public static string ClearingDiscoveryQueue {
            get {
                return ResourceManager.GetString("ClearingDiscoveryQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Content:
        ///{0}.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Done!.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Done matching Steam items, round #{0}..
        /// </summary>
        public static string DoneActivelyMatchingItems {
            get {
                return ResourceManager.GetString("DoneActivelyMatchingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Done clearing Steam discovery queue #{0}..
        /// </summary>
        public static string DoneClearingDiscoveryQueue {
            get {
                return ResourceManager.GetString("DoneClearingDiscoveryQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter command: .
        /// </summary>
        public static string EnterCommand {
            get {
                return ResourceManager.GetString("EnterCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Aborted!.
        /// </summary>
        public static string ErrorAborted {
            get {
                return ResourceManager.GetString("ErrorAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Access denied!.
        /// </summary>
        public static string ErrorAccessDenied {
            get {
                return ResourceManager.GetString("ErrorAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your bot config is invalid. Please verify content of {0} and try again!.
        /// </summary>
        public static string ErrorBotConfigInvalid {
            get {
                return ResourceManager.GetString("ErrorBotConfigInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Config directory could not be found, aborting!.
        /// </summary>
        public static string ErrorConfigDirectoryNotFound {
            get {
                return ResourceManager.GetString("ErrorConfigDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configured {0} property is invalid: {1}.
        /// </summary>
        public static string ErrorConfigPropertyInvalid {
            get {
                return ResourceManager.GetString("ErrorConfigPropertyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Persistent database could not be loaded, if issue persists, please remove {0} in order to recreate the database!.
        /// </summary>
        public static string ErrorDatabaseInvalid {
            get {
                return ResourceManager.GetString("ErrorDatabaseInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ASF V{0} has run into fatal exception before core logging module was even able to initialize!.
        /// </summary>
        public static string ErrorEarlyFatalExceptionInfo {
            get {
                return ResourceManager.GetString("ErrorEarlyFatalExceptionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exception: {0}() {1}
        ///StackTrace:
        ///{2}.
        /// </summary>
        public static string ErrorEarlyFatalExceptionPrint {
            get {
                return ResourceManager.GetString("ErrorEarlyFatalExceptionPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exiting with nonzero error code!.
        /// </summary>
        public static string ErrorExitingWithNonZeroErrorCode {
            get {
                return ResourceManager.GetString("ErrorExitingWithNonZeroErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Request failing: {0}.
        /// </summary>
        public static string ErrorFailingRequest {
            get {
                return ResourceManager.GetString("ErrorFailingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This function is available only in headless mode!.
        /// </summary>
        public static string ErrorFunctionOnlyInHeadlessMode {
            get {
                return ResourceManager.GetString("ErrorFunctionOnlyInHeadlessMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Global config could not be loaded. Make sure that {0} exists and is valid! Follow &apos;setting up&apos; guide on the wiki if you&apos;re confused..
        /// </summary>
        public static string ErrorGlobalConfigNotLoaded {
            get {
                return ResourceManager.GetString("ErrorGlobalConfigNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Global config file has been removed!.
        /// </summary>
        public static string ErrorGlobalConfigRemoved {
            get {
                return ResourceManager.GetString("ErrorGlobalConfigRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your provided CurrentCulture is invalid, ASF will keep running with the default one!.
        /// </summary>
        public static string ErrorInvalidCurrentCulture {
            get {
                return ResourceManager.GetString("ErrorInvalidCurrentCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} is empty!.
        /// </summary>
        public static string ErrorIsEmpty {
            get {
                return ResourceManager.GetString("ErrorIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} is invalid!.
        /// </summary>
        public static string ErrorIsInvalid {
            get {
                return ResourceManager.GetString("ErrorIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No bots are defined. Did you forget to configure your ASF? Follow &apos;setting up&apos; guide on the wiki if you&apos;re confused..
        /// </summary>
        public static string ErrorNoBotsDefined {
            get {
                return ResourceManager.GetString("ErrorNoBotsDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} is null!.
        /// </summary>
        public static string ErrorObjectIsNull {
            get {
                return ResourceManager.GetString("ErrorObjectIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parsing {0} failed!.
        /// </summary>
        public static string ErrorParsingObject {
            get {
                return ResourceManager.GetString("ErrorParsingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Request failed after {0} attempts!.
        /// </summary>
        public static string ErrorRequestFailedTooManyTimes {
            get {
                return ResourceManager.GetString("ErrorRequestFailedTooManyTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ASF process is already running for this working directory, aborting!.
        /// </summary>
        public static string ErrorSingleInstanceRequired {
            get {
                return ResourceManager.GetString("ErrorSingleInstanceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not check latest version!.
        /// </summary>
        public static string ErrorUpdateCheckFailed {
            get {
                return ResourceManager.GetString("ErrorUpdateCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not proceed with update because there is no asset that relates to currently running version! Automatic update to that version is not possible..
        /// </summary>
        public static string ErrorUpdateNoAssetForThisVersion {
            get {
                return ResourceManager.GetString("ErrorUpdateNoAssetForThisVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not proceed with an update because that version doesn&apos;t include any assets!.
        /// </summary>
        public static string ErrorUpdateNoAssets {
            get {
                return ResourceManager.GetString("ErrorUpdateNoAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Received a request for user input, but process is running in headless mode!.
        /// </summary>
        public static string ErrorUserInputRunningInHeadlessMode {
            get {
                return ResourceManager.GetString("ErrorUserInputRunningInHeadlessMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Executing....
        /// </summary>
        public static string Executing {
            get {
                return ResourceManager.GetString("Executing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exiting....
        /// </summary>
        public static string Exiting {
            get {
                return ResourceManager.GetString("Exiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We have a total of {0} games ({1} cards) left to farm (~{2} remaining)....
        /// </summary>
        public static string GamesToIdle {
            get {
                return ResourceManager.GetString("GamesToIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Global config file has been changed!.
        /// </summary>
        public static string GlobalConfigChanged {
            get {
                return ResourceManager.GetString("GlobalConfigChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Farming finished!.
        /// </summary>
        public static string IdlingFinished {
            get {
                return ResourceManager.GetString("IdlingFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finished farming: {0} ({1}) after {2} of playtime!.
        /// </summary>
        public static string IdlingFinishedForGame {
            get {
                return ResourceManager.GetString("IdlingFinishedForGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finished farming games: {0}.
        /// </summary>
        public static string IdlingFinishedForGames {
            get {
                return ResourceManager.GetString("IdlingFinishedForGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Farming {0} ({1}) is temporarily disabled, as ASF is not able to play that game at the moment..
        /// </summary>
        public static string IdlingGameNotPossible {
            get {
                return ResourceManager.GetString("IdlingGameNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Farming status for {0} ({1}): {2} cards remaining.
        /// </summary>
        public static string IdlingStatusForGame {
            get {
                return ResourceManager.GetString("IdlingStatusForGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Farming stopped!.
        /// </summary>
        public static string IdlingStopped {
            get {
                return ResourceManager.GetString("IdlingStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ignoring this request, as permanent pause is enabled!.
        /// </summary>
        public static string IgnoredPermanentPauseEnabled {
            get {
                return ResourceManager.GetString("IgnoredPermanentPauseEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ignoring trade: {0}.
        /// </summary>
        public static string IgnoringTrade {
            get {
                return ResourceManager.GetString("IgnoringTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Initializing {0}....
        /// </summary>
        public static string Initializing {
            get {
                return ResourceManager.GetString("Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Interactive console is now active, type &apos;c&apos; in order to enter command mode..
        /// </summary>
        public static string InteractiveConsoleEnabled {
            get {
                return ResourceManager.GetString("InteractiveConsoleEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Interactive console is not available due to missing {0} config property..
        /// </summary>
        public static string InteractiveConsoleNotAvailable {
            get {
                return ResourceManager.GetString("InteractiveConsoleNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IPC config has been changed!.
        /// </summary>
        public static string IPCConfigChanged {
            get {
                return ResourceManager.GetString("IPCConfigChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IPC server ready!.
        /// </summary>
        public static string IPCReady {
            get {
                return ResourceManager.GetString("IPCReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Starting IPC server....
        /// </summary>
        public static string IPCStarting {
            get {
                return ResourceManager.GetString("IPCStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logging in to {0}....
        /// </summary>
        public static string LoggingIn {
            get {
                return ResourceManager.GetString("LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No bots are running, exiting....
        /// </summary>
        public static string NoBotsAreRunning {
            get {
                return ResourceManager.GetString("NoBotsAreRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nothing found!.
        /// </summary>
        public static string NothingFound {
            get {
                return ResourceManager.GetString("NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We don&apos;t have anything to farm on this account!.
        /// </summary>
        public static string NothingToIdle {
            get {
                return ResourceManager.GetString("NothingToIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Now farming: {0} ({1}).
        /// </summary>
        public static string NowIdling {
            get {
                return ResourceManager.GetString("NowIdling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Now farming: {0}.
        /// </summary>
        public static string NowIdlingList {
            get {
                return ResourceManager.GetString("NowIdlingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Playing is currently unavailable, we&apos;ll try again later!.
        /// </summary>
        public static string PlayingNotAvailable {
            get {
                return ResourceManager.GetString("PlayingNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please wait....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} has been loaded successfully!.
        /// </summary>
        public static string PluginLoaded {
            get {
                return ResourceManager.GetString("PluginLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading {0} V{1}....
        /// </summary>
        public static string PluginLoading {
            get {
                return ResourceManager.GetString("PluginLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You&apos;ve loaded one or multiple custom plugins into ASF. Since we&apos;re unable to offer support for modded setups, please contact the appropriate developers of the plugins that you decided to use in case of any issues..
        /// </summary>
        public static string PluginsWarning {
            get {
                return ResourceManager.GetString("PluginsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refreshing our session!.
        /// </summary>
        public static string RefreshingOurSession {
            get {
                return ResourceManager.GetString("RefreshingOurSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rejecting trade: {0}.
        /// </summary>
        public static string RejectingTrade {
            get {
                return ResourceManager.GetString("RejectingTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restarting....
        /// </summary>
        public static string Restarting {
            get {
                return ResourceManager.GetString("Restarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Result: {0}.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Starting....
        /// </summary>
        public static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Still farming: {0} ({1}).
        /// </summary>
        public static string StillIdling {
            get {
                return ResourceManager.GetString("StillIdling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Still farming: {0}.
        /// </summary>
        public static string StillIdlingList {
            get {
                return ResourceManager.GetString("StillIdlingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stopped farming: {0} ({1}).
        /// </summary>
        public static string StoppedIdling {
            get {
                return ResourceManager.GetString("StoppedIdling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stopped farming: {0}.
        /// </summary>
        public static string StoppedIdlingList {
            get {
                return ResourceManager.GetString("StoppedIdlingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Success!.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Target bot instance is not connected!.
        /// </summary>
        public static string TargetBotNotConnected {
            get {
                return ResourceManager.GetString("TargetBotNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ASF will attempt to use your preferred {0} culture, but translation into that language is only {1} complete. Perhaps you could help us improve the ASF translation for your language?.
        /// </summary>
        public static string TranslationIncomplete {
            get {
                return ResourceManager.GetString("TranslationIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown command!.
        /// </summary>
        public static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unlocking parental account....
        /// </summary>
        public static string UnlockingParentalAccount {
            get {
                return ResourceManager.GetString("UnlockingParentalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unused keys: {0}.
        /// </summary>
        public static string UnusedKeys {
            get {
                return ResourceManager.GetString("UnusedKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Checking for new version....
        /// </summary>
        public static string UpdateCheckingNewVersion {
            get {
                return ResourceManager.GetString("UpdateCheckingNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cleaning up old files after update....
        /// </summary>
        public static string UpdateCleanup {
            get {
                return ResourceManager.GetString("UpdateCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloading new version: {0} ({1} MB)... While waiting, consider donating if you appreciate the work being done! :).
        /// </summary>
        public static string UpdateDownloadingNewVersion {
            get {
                return ResourceManager.GetString("UpdateDownloadingNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update process finished!.
        /// </summary>
        public static string UpdateFinished {
            get {
                return ResourceManager.GetString("UpdateFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New ASF version is available! Consider updating yourself!.
        /// </summary>
        public static string UpdateNewVersionAvailable {
            get {
                return ResourceManager.GetString("UpdateNewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Local version: {0} | Remote version: {1}.
        /// </summary>
        public static string UpdateVersionInfo {
            get {
                return ResourceManager.GetString("UpdateVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter your 2FA code from your Steam authenticator app: .
        /// </summary>
        public static string UserInputSteam2FA {
            get {
                return ResourceManager.GetString("UserInputSteam2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter SteamGuard auth code that was sent on your e-mail: .
        /// </summary>
        public static string UserInputSteamGuard {
            get {
                return ResourceManager.GetString("UserInputSteamGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter your Steam login: .
        /// </summary>
        public static string UserInputSteamLogin {
            get {
                return ResourceManager.GetString("UserInputSteamLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter Steam parental code: .
        /// </summary>
        public static string UserInputSteamParentalCode {
            get {
                return ResourceManager.GetString("UserInputSteamParentalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter your Steam password: .
        /// </summary>
        public static string UserInputSteamPassword {
            get {
                return ResourceManager.GetString("UserInputSteamPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not get badges&apos; information, we will try again later!.
        /// </summary>
        public static string WarningCouldNotCheckBadges {
            get {
                return ResourceManager.GetString("WarningCouldNotCheckBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not check cards status for: {0} ({1}), we will try again later!.
        /// </summary>
        public static string WarningCouldNotCheckCardsStatus {
            get {
                return ResourceManager.GetString("WarningCouldNotCheckCardsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Usage of {0} is deprecated and will be removed in future versions of the program. Please use {1} instead..
        /// </summary>
        public static string WarningDeprecated {
            get {
                return ResourceManager.GetString("WarningDeprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You&apos;re running more personal bot accounts than our upper recommended limit ({0}). Be advised that this setup is not supported and might cause various Steam-related issues, including account suspensions. Check out the FAQ for more details..
        /// </summary>
        public static string WarningExcessiveBotsCount {
            get {
                return ResourceManager.GetString("WarningExcessiveBotsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed!.
        /// </summary>
        public static string WarningFailed {
            get {
                return ResourceManager.GetString("WarningFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed due to error: {0}.
        /// </summary>
        public static string WarningFailedWithError {
            get {
                return ResourceManager.GetString("WarningFailedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ASF detected ID mismatch for {0} ({1}) and will use ID of {2} instead..
        /// </summary>
        public static string WarningIdlingGameMismatch {
            get {
                return ResourceManager.GetString("WarningIdlingGameMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You&apos;re using a version that is newer than the latest released version for your update channel. Please note that pre-release versions are meant for users who know how to report bugs, deal with issues and give feedback - no technical support will be given..
        /// </summary>
        public static string WarningPreReleaseVersion {
            get {
                return ResourceManager.GetString("WarningPreReleaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please review our privacy policy section on the wiki if you&apos;re concerned about what ASF is in fact doing!.
        /// </summary>
        public static string WarningPrivacyPolicy {
            get {
                return ResourceManager.GetString("WarningPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown command-line argument: {0}.
        /// </summary>
        public static string WarningUnknownCommandLineArgument {
            get {
                return ResourceManager.GetString("WarningUnknownCommandLineArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Received unknown value for {0}, please report this: {1}.
        /// </summary>
        public static string WarningUnknownValuePleaseReport {
            get {
                return ResourceManager.GetString("WarningUnknownValuePleaseReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You&apos;re attempting to run {0} variant of ASF in an unsupported environment: {1}. Supply --ignore-unsupported-environment argument if you really know what you&apos;re doing..
        /// </summary>
        public static string WarningUnsupportedEnvironment {
            get {
                return ResourceManager.GetString("WarningUnsupportedEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Workaround for {0} bug has been triggered..
        /// </summary>
        public static string WarningWorkaroundTriggered {
            get {
                return ResourceManager.GetString("WarningWorkaroundTriggered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на It looks like it&apos;s your first launch of the program, welcome!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
