// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Roulette.Context;

namespace Roulette.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201129234738_abdfd")]
    partial class abdfd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Roulette.Models.SteamUsersModel", b =>
                {
                    b.Property<string>("SteamID")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<double>("Balance")
                        .HasColumnType("double");

                    b.HasKey("SteamID");

                    b.ToTable("SteamUsers");

                    b.HasData(
                        new
                        {
                            SteamID = "76561100000000000",
                            Balance = 0.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
