name: Deploy Workflow

on: 
  push:
    branches: [ master ]
    
jobs:
  job_one:
     name: Deploy
     runs-on: ubuntu-latest
     steps:
     -  name: testing ssh connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_SECRET }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/Roulette
            git pull origin master
            git status
            dotnet restore
            dotnet build --configuration Debug
            dotnet publish -c Debug -o '/home/Roulette/server' 
